export const LS_ACCESS_TOKEN = "LS_ACCESS_TOKEN";
export const LS_REFRESH_TOKEN = "LS_REFRESH_TOKEN";
export const LS_AUTH_USER = "LS_AUTH_USER";
export const LS_CODE_EDITOR = "LS_CODE_EDITOR";
export const LS_GEN_USER_CSV_LOG = "LS_GEN_USER_CSV_LOG";