export const SET_CONTEST_PARAMS = 'SUBFILTER_SET_CT_PARAMS';
export const SET_PUBLIC_PARAMS = 'SUBFILTER_SET_PB_PARAMS';

export const CLEAR_CONTEST_PARAMS = 'SUBFILTER_CLEAR_CT_PARAMS';
export const CLEAR_PUBLIC_PARAMS = 'SUBFILTER_CLEAR_PB_PARAMS';

export const CLEAR_ALL_PARAMS = 'SUBFILTER_CLEAR_A_PARAMS';

export const NO_CONTEST_KEY = 'P';
